apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terraform-canvas.fullname" . }}-back
  labels:
    app: {{ include "terraform-canvas.name" . }}-back
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "terraform-canvas.name" . }}-back
  template:
    metadata:
      labels:
        app: {{ include "terraform-canvas.name" . }}-back
    spec:
      serviceAccountName: {{ include "terraform-canvas.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-back
          image: iad.ocir.io/idklmfs5zwub/terraform_canvas:5af0ae1816bc25222ae029d69fc23846d605a6d8
          ports:
            - name: http
              containerPort: {{ .Values.backend.lb.http.targetPort}}
              protocol: TCP
          env:
            - name: tenancyID
              valueFrom:
                secretKeyRef:
                  name: oci-sdk
                  key: tenancyID
            - name: userID
              valueFrom:
                secretKeyRef:
                  name: oci-sdk
                  key: userID
            - name: fingerprint
              valueFrom:
                secretKeyRef:
                  name: oci-sdk
                  key: fingerprint
            - name: privateKey
              valueFrom:
                secretKeyRef:
                  name: oci-sdk
                  key: privateKey
            - name: compartmentID
              valueFrom:
                secretKeyRef:
                  name: oci-sdk
                  key: compartmentID
            - name: privateKeyPass
              valueFrom:
                secretKeyRef:
                  name: oci-sdk
                  key: privateKeyPass
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: JWT_SECRET_KEY
            - name: JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT
            - name: JWT_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: JWT_REFRESH_KEY
            - name: JWT_REFRESH_KEY_EXPIRE_HOURS_COUNT
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: JWT_REFRESH_KEY_EXPIRE_HOURS_COUNT
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-sdk
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-sdk
                  key: AWS_SECRET_KEY
            - name: region
              valueFrom:
                configMapKeyRef:
                  name: oci-sdk
                  key: region
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: aws-sdk
                  key: AWS_REGION
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: server-set
                  key: SERVER_HOST
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: server-set
                  key: SERVER_PORT
            - name: SERVER_READ_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: server-set
                  key: SERVER_READ_TIMEOUT

---
apiVersion: v1
kind: Service
metadata:
  name: "backend-cluster"
  labels:
    {{- include "terraform-canvas.labels" . | nindent 4 }}-back
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.http.servicePort }}
      targetPort: {{ .Values.backend.service.http.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "terraform-canvas.name" . }}-back
