apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terraform-canvas.fullname" . }}-front
  labels:
    app: {{ include "terraform-canvas.name" . }}-front
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "terraform-canvas.name" . }}-front
  template:
    metadata:
      labels:
        app: {{ include "terraform-canvas.name" . }}-front
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: fe-config
      serviceAccountName: {{ include "terraform-canvas.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}-front
        image: iad.ocir.io/idklmfs5zwub/terraform_canvas:a4a2744afe9a1ffc21f821a47c2ad540cd3d219e
        ports:
        - name: http
          containerPort: {{ .Values.frontend.lb.http.targetPort}}
          protocol: TCP
        volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
---
apiVersion: v1
kind: Service
metadata:
  name: "front-service"
  labels:
    {{- include "terraform-canvas.labels" . | nindent 4 }}-front
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - name: http
    port: {{ .Values.frontend.service.http.servicePort }}
    targetPort: {{ .Values.frontend.service.http.targetPort }}
    protocol: TCP
  selector:
    app: {{ include "terraform-canvas.name" . }}-front

