apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terraform-canvas.fullname" . }}-front
  labels:
    app: {{ include "terraform-canvas.name" . }}-front
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "terraform-canvas.name" . }}-front
  template:
    metadata:
      labels:
        app: {{ include "terraform-canvas.name" . }}-front
    spec:
      serviceAccountName: {{ include "terraform-canvas.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}-front
        image: iad.ocir.io/id09nrqj84t0/terraform_canvas:772d6efddb8a605537dfdf217f858a263599f0bc
        ports:
        - name: http
          containerPort: {{ .Values.frontend.lb.http.targetPort}}
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: "front-service"
  labels:
    {{- include "terraform-canvas.labels" . | nindent 4 }}-front
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - name: http
    port: {{ .Values.frontend.service.http.servicePort }}
    targetPort: {{ .Values.frontend.service.http.targetPort }}
    protocol: TCP
  selector:
    app: {{ include "terraform-canvas.name" . }}-front

---
apiVersion: v1
kind: Service
metadata:
  name: "front-lb"
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-backend-protocol: "HTTP"
  labels:
    {{- include "terraform-canvas.labels" . | nindent 4 }}-front
spec:
  type: {{ .Values.frontend.lb.type }}
  ports:
  - name: http
    port: {{ .Values.frontend.lb.http.servicePort }}
    targetPort: {{ .Values.frontend.lb.http.targetPort }}
  selector:
    app: {{ include "terraform-canvas.name" . }}-front